tunnel: dda22c8c-6a6a-4669-84e8-74fd1474e75e
credentials-file: /Users/dev/.cloudflared/dda22c8c-6a6a-4669-84e8-74fd1474e75e.json
ingress:
  - hostname: carecircle.assistedly.ai
    service: http://127.0.0.1:3002
  - service: http_status:404
protocol: http2
